import { Store, Product } from './types';

export const mockStores: Store[] = [
  {
    id: '1',
    name: 'Premium Liquor House',
    rating: 4.8,
    deliveryTime: '25-35 min',
    distance: '1.2 km',
    isOpen: true,
    licenseNumber: 'LIC-2024-001',
  },
  {
    id: '2',
    name: 'Local Spirits Co.',
    rating: 4.6,
    deliveryTime: '30-40 min',
    distance: '2.1 km',
    isOpen: true,
    licenseNumber: 'LIC-2024-002',
  },
  {
    id: '3',
    name: 'The Bottle Shop',
    rating: 4.5,
    deliveryTime: '35-45 min',
    distance: '3.5 km',
    isOpen: false,
    licenseNumber: 'LIC-2024-003',
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Kingfisher Premium',
    category: 'Beer',
    price: 650,
    image: '🍺',
    proof: 5.2,
    size: '650ml',
    brand: 'Kingfisher',
    inStock: true,
    storeId: '1',
  },
  {
    id: '2',
    name: 'Johnnie Walker Black Label',
    category: 'Spirits',
    price: 3200,
    image: '🥃',
    proof: 40,
    size: '750ml',
    brand: 'Johnnie Walker',
    inStock: true,
    storeId: '1',
  },
  {
    id: '3',
    name: 'Red Wine Cabernet',
    category: 'Wine',
    price: 1500,
    image: '🍷',
    proof: 13.5,
    size: '750ml',
    brand: 'Château Reserve',
    inStock: true,
    storeId: '1',
  },
  {
    id: '4',
    name: 'Breezer Mango',
    category: 'RTDs',
    price: 300,
    image: '🧃',
    proof: 4.8,
    size: '275ml',
    brand: 'Breezer',
    inStock: true,
    storeId: '1',
  },
  {
    id: '5',
    name: 'Mixed Nuts & Chips',
    category: 'Snacks',
    price: 250,
    image: '🥜',
    proof: 0,
    size: '200g',
    brand: 'Snackz',
    inStock: true,
    storeId: '1',
  },
  {
    id: '6',
    name: 'Budweiser',
    category: 'Beer',
    price: 600,
    image: '🍺',
    proof: 5,
    size: '500ml',
    brand: 'Budweiser',
    inStock: true,
    storeId: '2',
  },
  {
    id: '7',
    name: 'Grey Goose Vodka',
    category: 'Spirits',
    price: 3500,
    image: '🥃',
    proof: 40,
    size: '750ml',
    brand: 'Grey Goose',
    inStock: true,
    storeId: '2',
  },
];